[project]
name = "blendify"
version = "0.0.1"
description = "Create dynamic, unique playlists for Spotify using the power of AI."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.82.1",
    "spotipy>=2.25.1",
]
